#!/bin/bash

# -----------------------------
# System Information Report Script

echo ""

# Get basic identifiers
HOSTNAME=$(hostname)              # Get the system's hostname
USERNAME=$(whoami)               # Get the name of the current user running the script
DATE=$(date)                     # Get current date and time

# Collect system information

# Get the operating system name and version from /etc/os-release
OS=$(source /etc/os-release && echo "$PRETTY_NAME")

# Get the system uptime in a human-readable format
UPTIME=$(uptime -p)

# Get CPU model and make (first processor listed)
CPU=$(lshw -class processor | grep "product" | head -1 | cut -d: -f2 | sed 's/^ //')

# Get total installed RAM (human-readable format)
RAM=$(free -h | awk '/Mem:/ {print $2}')

# Get disk make, model, and size for all disks
DISKS=$(lshw -class disk | grep -E "product|size" | paste -sd "," - | sed 's/product: //g; s/size: //g')

# Get video card (GPU) make and model
VIDEO=$(lshw -class display | grep "product" | head -1 | cut -d: -f2 | sed 's/^ //')

# Get the IP address of the interface connected to the default gateway
HOST_IP=$(ip route get 1.1.1.1 | awk '{print $7; exit}')

# Get the default gateway IP address
GATEWAY=$(ip route | grep default | awk '{print $3}')

# Get DNS server IP addresses from resolv.conf
DNS=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}' | paste -sd "," -)


# Collect system status

# List users currently logged in, remove duplicates, and format as comma-separated list
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

# Show free disk space for all mounted filesystems in /MOUNTPOINT: SIZE format
DISK_SPACE=$(df -h --output=target,avail | grep -v "Mounted" | awk '{print $1 ": " $2}' | paste -sd ", " -)

# Count number of running processes
PROCESS_COUNT=$(ps ax | wc -l)

# Get load averages (1 min, 5 min, 15 min)
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | sed 's/ //g')

# Get list of listening network ports, sorted and unique
PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd "," -)

# Get UFW firewall status (requires sudo)
UFW_STATUS=$(sudo ufw status | head -n 1)


# Display the report using a heredoc block
cat <<EOF

System Report for $HOSTNAME generated by $USERNAME on $DATE

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_IP
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVG
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS

EOF


echo ""
